apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: focusflow
  labels:
    app: payment-service
    version: v1
    component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
        component: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: payment-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: payment-service
        image: focusflow/payment-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: payment-service-secrets
              key: database-url
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payment-service-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-service-secrets
              key: stripe-webhook-secret
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            configMapKeyRef:
              name: payment-service-config
              key: stripe-publishable-key
        envFrom:
        - configMapRef:
            name: payment-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: app-logs
        emptyDir: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: focusflow
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: focusflow
data:
  DATABASE_MAX_CONNECTIONS: "20"
  DATABASE_IDLE_TIMEOUT: "30000"
  DATABASE_CONNECTION_TIMEOUT: "60000"
  CORS_ORIGIN: '["https://app.focusflow.com","https://admin.focusflow.com"]'
  RATE_LIMIT_MAX: "100"
  RATE_LIMIT_TIME_WINDOW: "60000"
  API_PREFIX: "/api/v1"
  ENABLE_SWAGGER: "false"
  HEALTH_CHECK_INTERVAL: "30000"
  PAYMENT_TIMEOUT: "30000"
  IDEMPOTENCY_TTL: "86400000"
  stripe-publishable-key: "pk_live_your_publishable_key_here"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: focusflow
type: Opaque
data:
  # Base64 encoded values
  database-url: # postgresql://username:password@host:port/database
  stripe-secret-key: # sk_live_your_secret_key_here
  stripe-webhook-secret: # whsec_your_webhook_secret_here
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: focusflow
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payment-service-network-policy
  namespace: focusflow
spec:
  podSelector:
    matchLabels:
      app: payment-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: database
    ports:
    - protocol: TCP
      port: 5432
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS for Stripe API
    - protocol: TCP
      port: 53   # DNS
    - protocol: UDP
      port: 53   # DNS